// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { LocationProvider } from "@/context/LocationContext";

export const metadata = {
  title:
    "SparkPro Electricians | Professional Electrician Services At Your Doorstep",
  description:
    "Book certified electricians for fan, AC, wiring, lighting, switch & socket and inverter services. Same day service, transparent pricing.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-body antialiased">
        <CartProvider>
          <LocationProvider>
            <Toaster
              position="top-center"
              toastOptions={{
                style: {
                  background: "#0F172A",
                  color: "#fff",
                  fontSize: "14px",
                  borderRadius: "10px",
                },
                success: {
                  iconTheme: { primary: "#FFA800", secondary: "#0F172A" },
                },
              }}
            />
            <Navbar />
            <main className="min-h-screen">{children}</main>
            <Footer />
          </LocationProvider>
        </CartProvider>
      </body>
    </html>
  );
}
